# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 568)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(40, 290, 111, 31))
        self.checkBox.setObjectName("checkBox")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(510, 20, 271, 181))
        self.graphicsView.setObjectName("graphicsView")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(40, 250, 151, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 351, 221))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_resistencia = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_resistencia.setGeometry(QtCore.QRect(20, 150, 113, 20))
        self.lineEdit_resistencia.setObjectName("lineEdit_resistencia")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(180, 40, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_V0 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_V0.setGeometry(QtCore.QRect(180, 60, 113, 20))
        self.lineEdit_V0.setObjectName("lineEdit_V0")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(180, 100, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_I0 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_I0.setGeometry(QtCore.QRect(180, 120, 113, 20))
        self.lineEdit_I0.setObjectName("lineEdit_I0")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_Indutor = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Indutor.setGeometry(QtCore.QRect(20, 90, 113, 20))
        self.lineEdit_Indutor.setObjectName("lineEdit_Indutor")
        self.lineEdit_capacitor = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_capacitor.setGeometry(QtCore.QRect(20, 40, 113, 20))
        self.lineEdit_capacitor.setObjectName("lineEdit_capacitor")
        self.gerarResultados = QtWidgets.QPushButton(self.centralwidget)
        self.gerarResultados.setGeometry(QtCore.QRect(280, 250, 91, 31))
        self.gerarResultados.setObjectName("gerarResultados")
        self.canvasGraph = QtWidgets.QWidget(self.centralwidget)
        self.canvasGraph.setGeometry(QtCore.QRect(480, 260, 301, 241))
        self.canvasGraph.setAutoFillBackground(False)
        self.canvasGraph.setObjectName("canvasGraph")
        self.message = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.message.setGeometry(QtCore.QRect(20, 340, 431, 161))
        self.message.setTabChangesFocus(True)
        self.message.setOverwriteMode(False)
        self.message.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.message.setBackgroundVisible(False)
        self.message.setObjectName("message")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox.currentIndexChanged['int'].connect(self.graphicsView.invalidateScene)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_V0, self.lineEdit_capacitor)
        MainWindow.setTabOrder(self.lineEdit_capacitor, self.lineEdit_Indutor)
        MainWindow.setTabOrder(self.lineEdit_Indutor, self.lineEdit_resistencia)
        MainWindow.setTabOrder(self.lineEdit_resistencia, self.lineEdit_I0)
        MainWindow.setTabOrder(self.lineEdit_I0, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.checkBox)
        MainWindow.setTabOrder(self.checkBox, self.graphicsView)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox.setText(_translate("MainWindow", "Plotar Gráfico"))
        self.comboBox.setItemText(0, _translate("MainWindow", "RLC em Série sem Fonte"))
        self.comboBox.setItemText(1, _translate("MainWindow", "RLC em Paralelo sem Fonte"))
        self.comboBox.setItemText(2, _translate("MainWindow", "RLC em Série com Fonte"))
        self.comboBox.setItemText(3, _translate("MainWindow", "RLC em Paralelo com Fonte"))
        self.groupBox.setTitle(_translate("MainWindow", "Entradas"))
        self.label_3.setText(_translate("MainWindow", "Resistência"))
        self.label_4.setText(_translate("MainWindow", "Tensão Inicial no Capacitor"))
        self.label_5.setText(_translate("MainWindow", "Corrente Inicial no Indutor"))
        self.label_2.setText(_translate("MainWindow", "Indutância"))
        self.label.setText(_translate("MainWindow", "Capacitância"))
        self.gerarResultados.setText(_translate("MainWindow", "GERAR!"))
        self.message.setPlaceholderText(_translate("MainWindow", "Resultado"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

